import type { Course } from "./types";

export const sampleCourses: Course[] = [
  {
    id: "c1",
    code: "AM1",
    name: "Analisis Matematico I",
    year: 1,
    grade: null,
    passed: true,
    status: "regular",
  },
  {
    id: "c2",
    code: "AGA",
    name: "Algebra y Geometria Analitica",
    year: 1,
    grade: null,
    passed: true,
    status: "aprobado",
  },
  {
    id: "c3",
    code: "F1",
    name: "Física I",
    year: 1,
    grade: null,
    passed: true,
    status: "promocionado",
  },
  {
    id: "c4",
    code: "I1",
    name: "Ingles I",
    year: 1,
    grade: null,
    passed: true,
    status: "aprobado",
  },
  {
    id: "c5",
    code: "MAD",
    name: "Matemática Discreta",
    year: 1,
    grade: null,
    passed: true,
    status: "promocionado",
  },
  {
    id: "c6",
    code: "AEDD",
    name: "Algoritmos y Estructuras de Datos",
    year: 1,
    grade: null,
    passed: true,
    status: "promocionado",
  },
  {
    id: "c7",
    code: "ADC",
    name: "Arquitectura de Computadoras",
    year: 1,
    grade: null,
    passed: true,
    status: "aprobado",
  },
  {
    id: "c8",
    code: "SYO",
    name: "Sistemas y Organizaciones",
    year: 1,
    grade: null,
    passed: true,
    status: "promocionado",
  },
  {
    id: "c9",
    code: "AM2",
    name: "Analisis Matematico II",
    year: 2,
    grade: null,
    passed: true,
    status: "regular",
  },
  {
    id: "c10",
    code: "F2",
    name: "Fisica II",
    year: 2,
    grade: null,
    passed: false,
    status: "promocionado",
  },
  {
    id: "c11",
    code: "IYS",
    name: "Ingenieria y Sociedad",
    year: 2,
    grade: null,
    passed: true,
    status: "promocionado",
  },
  {
    id: "c12",
    code: "I2",
    name: "Ingles II",
    year: 2,
    grade: null,
    passed: false,
    status: "aprobado",
  },
  {
    id: "c13",
    code: "SSL",
    name: "Sintaxis y Semántica de los Lenguajes",
    year: 2,
    grade: null,
    passed: false,
    status: "promocionado",
  },
  {
    id: "c14",
    code: "PDP",
    name: "Paradigmas de Programación",
    year: 2,
    grade: null,
    passed: false,
    status: "promocionado",
  },
  {
    id: "c15",
    code: "SO",
    name: "Sistemas Operativos",
    year: 2,
    grade: null,
    passed: true,
    status: "promocionado",
  },
  {
    id: "c16",
    code: "ADS",
    name: "Analisis de Sistemas",
    year: 2,
    hours: 8,
    grade: null,
    passed: false,
    status: "promocionado",
  },
  {
    id: "c17",
    code: "PYE",
    name: "Probabilidad y Estadistica",
    year: 3,
    grade: null,
    passed: false,
    status: "cursando",
  },
  {
    id: "c18",
    code: "ECO",
    name: "Economia",
    year: 3,
    grade: null,
    passed: false,
    status: "promocionado",
  },
  {
    id: "c19",
    code: "BDD",
    name: "Bases de Datos",
    year: 3,
    grade: null,
    passed: false,
    status: "promocionado",
  },
  {
    id: "c20",
    code: "DeSo",
    name: "Desarrollo de Software",
    year: 3,
    grade: null,
    passed: false,
    status: "cursando",
  },
  {
    id: "c21",
    code: "CDD",
    name: "Comunicacion de Datos",
    year: 3,
    grade: null,
    passed: false,
    status: "regular",
  },
  {
    id: "c22",
    code: "MS",
    name: "Matematica Superior",
    year: 3,
    grade: null,
    passed: false,
    status: "cursando",
  },
  {
    id: "c23",
    code: "DDS",
    name: "Diseño de Sistemas",
    year: 4,
    grade: null,
    passed: false,
    status: "cursando",
  },
  {
    id: "c24",
    code: "LEG",
    name: "Legislacion",
    year: 4,
    grade: null,
    passed: false,
    status: "puede cursar",
  },
  {
    id: "c25",
    code: "ICS",
    name: "Ingenieria y Calidad de Software",
    year: 4,
    grade: null,
    passed: false,
    status: "puede cursar",
  },
  {
    id: "c26",
    code: "RDD",
    name: "Redes de Datos",
    year: 4,
    grade: null,
    passed: false,
    status: "puede cursar",
  },
  {
    id: "c27",
    code: "IO",
    name: "Investigacion Operativa",
    year: 4,
    grade: null,
    passed: false,
    status: "puede cursar",
  },
  {
    id: "c28",
    code: "SIM",
    name: "Simulacion",
    year: 4,
    grade: null,
    passed: false,
    status: "puede cursar",
  },
  {
    id: "c29",
    code: "TPA",
    name: "Tecnologias para la Automatizacion",
    year: 4,
    grade: null,
    passed: false,
    status: "puede cursar",
  },
  {
    id: "c30",
    code: "ADSS",
    name: "Administracion de Sistemas",
    year: 4,
    grade: null,
    passed: false,
    status: "no puede cursar",
  },
  {
    id: "c31",
    code: "IA",
    name: "Inteligencia Artificial",
    year: 5,
    grade: null,
    passed: false,
    status: "no puede cursar",
  },
  {
    id: "c32",
    code: "CDDD",
    name: "Ciencia de Datos",
    year: 5,
    grade: null,
    passed: false,
    status: "no puede cursar",
  },
  {
    id: "c33",
    code: "SDG",
    name: "Sistemas de Gestion",
    year: 5,
    grade: null,
    passed: false,
    status: "no puede cursar",
  },
  {
    id: "c34",
    code: "GG",
    name: "Gestion Gerencial",
    year: 5,
    grade: null,
    passed: false,
    status: "no puede cursar",
  },
  {
    id: "c35",
    code: "SDS",
    name: "Seguridad de los Sistemas",
    year: 5,
    grade: null,
    passed: false,
    status: "no puede cursar",
  },
  {
    id: "c36",
    code: "PF",
    name: "Proyecto Final",
    year: 5,
    grade: null,
    passed: false,
    status: "no puede cursar",
  },
];
